# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyskills" do
  version "0.3.3"

  on_macos do
    on_intel do
      sha256 "ed1044e245bae08b00f462d26ae462617216fe1a5bad8d53ca32de5128718489"
      url "https://github.com/alvinunreal/lazyskills/releases/download/v#{version}/lazyskills_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "61ffe4f76b55a482e519bd1720a550dc0e9c7f67472a507eaaa7735e5b72d0fd"
      url "https://github.com/alvinunreal/lazyskills/releases/download/v#{version}/lazyskills_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4abede48bbee79da8c7a2b119f7108595a8ef901a059cbd7976a4e30a3f52721"
      url "https://github.com/alvinunreal/lazyskills/releases/download/v#{version}/lazyskills_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7b4f02f0f447c19f5bf589709541f06804e1fd5c44a714a3a46174ec2d7e7ccb"
      url "https://github.com/alvinunreal/lazyskills/releases/download/v#{version}/lazyskills_Linux_arm64.tar.gz"
    end
  end

  name "lazyskills"
  desc "Mission control for agent skills to stay lazy."
  homepage "https://github.com/alvinunreal/lazyskills"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyskills"

  # No zap stanza required

end
