# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyskills" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "2d3166a2c0bb49fc71c7305691e42bec3972e41f3992f336fc357942ff8a92fe"
      url "https://github.com/alvinunreal/lazyskills/releases/download/v#{version}/lazyskills_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1e3206a14ac608064d1168d3b55e156294892442ba37d725a9296117e8ee4f34"
      url "https://github.com/alvinunreal/lazyskills/releases/download/v#{version}/lazyskills_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "27188c65e28861fd04b4e63c3fe67a2b34b2302e488195c780cb7a02ba37390e"
      url "https://github.com/alvinunreal/lazyskills/releases/download/v#{version}/lazyskills_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b0534d7de28a6fcd45a285cf47652523bb0bdcec5d657cade56369728d8c0156"
      url "https://github.com/alvinunreal/lazyskills/releases/download/v#{version}/lazyskills_Linux_arm64.tar.gz"
    end
  end

  name "lazyskills"
  desc "Mission control for agent skills to stay lazy."
  homepage "https://github.com/alvinunreal/lazyskills"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyskills"

  # No zap stanza required

end
