# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyskills" do
  version "1.1.0"

  on_macos do
    on_arm do
      sha256 "26140eb4abbca61b61567b9d326332497a7c25da1a2db7fa80b0ddd72857a40b"
      url "https://github.com/alvinunreal/lazyskills/releases/download/v#{version}/lazyskills_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "162e4e95420e6adfb6d0732b2e021ad6be1f80fafc71169e9311d8221cdce022"
      url "https://github.com/alvinunreal/lazyskills/releases/download/v#{version}/lazyskills_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "39df72539a28d6829ab7076f2fc8228f45873c840a98fd9dd23bd2e6804fba84"
      url "https://github.com/alvinunreal/lazyskills/releases/download/v#{version}/lazyskills_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "43e314bacc69752e8942eab05649be64e47ed62403c24bbc56ea2425cd063f72"
      url "https://github.com/alvinunreal/lazyskills/releases/download/v#{version}/lazyskills_Linux_x86_64.tar.gz"
    end
  end

  name "lazyskills"
  desc "Mission control for agent skills to stay lazy."
  homepage "https://github.com/alvinunreal/lazyskills"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyskills"

  # No zap stanza required
end
